---
# tasks file for chrisjohnson00.jackett

- name: Check if jackett version exists in /opt     
  stat: 
    path: "/opt/jackett/{{ chrisjohnson00_jackett_version }}"
  register: jackett_install_location

- file:
    path: "/opt/jackett/{{ chrisjohnson00_jackett_version }}"
    state: directory
    mode: 0755
  when: not jackett_install_location.stat.exists

- name: "download Jackett archive file"
  unarchive:
    src: "https://github.com/Jackett/Jackett/releases/download/{{ chrisjohnson00_jackett_version }}/Jackett.Binaries.Mono.tar.gz"
    dest: "/opt/jackett/{{ chrisjohnson00_jackett_version }}"
    remote_src: True
  when: not jackett_install_location.stat.exists

- name: Only run apt-get update if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ chrisjohnson00_jackett_packages }}"

- name: setup jackett user
  user:
    name: "{{ chrisjohnson00_jackett_user }}"

- name: check for systemd
  command: systemctl --version
  register: jackett_systemctl_version
  ignore_errors: yes

- name: add jackett.service
  template:
    src: jackett.service.ini
    dest: /lib/systemd/system/jackett.service
    mode: 0644
  become: yes
  when: jackett_systemctl_version.rc == 0
  notify:
    - jackett_reload_systemd
    - restart_jackett